server {
    listen 80;
    # server_name example.com; # 도메인

    # 프론트엔드 정적 파일 서빙
    location / {
        root   /usr/share/nginx/html; # Docker 컨테이너 내 빌드 파일 위치
        index  index.html index.htm;
        # 요청한 파일이 없으면 index.html을 보여주어 React Router가 처리하게 함
        try_files $uri $uri/ /index.html;
    }

    # 백엔드 API 요청 전달 (추후 삭제 예정)
    location /api/ {
        # 'backend-prod'는 docker-compose.yml에 정의할 백엔드 서비스 이름
        proxy_pass http://backend-prod:8124/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # 에러 페이지 설정
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}